config/routes.rb
Rails.application.routes.draw do
  resources :orders
  devise_for :users
	root 'listings#index'
  resources :listings do
  	resources :orders, only: [:new, :create]
  end
  get 'pages/about'
  get 'pages/contact'
  get 'seller', to: 'listings#seller'
  get 'sales', to: 'orders#sales'
  get 'purchases', to: 'orders#purchases'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  has_one_attached :image
  validates :image, :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  belongs_to :user
  has_many :orders
end

app/models/order.rb
class Order < ApplicationRecord
	validates :address, :city, :state, presence: true

	belongs_to :listing
	belongs_to :buyer, class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  has_many :listings, dependent: :destroy
  has_many :sales, class_name: "Order", foreign_key: "seller_id"
  has_many :purchases, class_name: "Order", foreign_key: "buyer_id"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, only: [:edit, :update, :destroy]



  def seller
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id  


    if current_user.recipient.blank?
      Stripe.api_key = ENV["STRIPE_API_KEY"]
      token = params[:stripeToken]

      recipient = Stripe::Account.create(
        type: 'custom',
        country: 'US',
        email: current_user.email,
        business_type: 'individual',
        individual: {
          email: current_user.email,
          first_name: current_user.name
        },
        tos_acceptance: {
          date: Time.now.to_i,
          ip: request.remote_ip
        },
        requested_capabilities: ['card_payments', 'transfers']
        )

      current_user.recipient = recipient.id
      current_user.save
    end

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else."
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")
  end


  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end


  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.buyer_id = current_user.id
    @order.listing_id = @listing.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create({
        source: token,
        amount: (@listing.price * 100).floor,
        currency: 'usd'
        })
      flash[:notice] = "Thanks for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    transfer = Stripe::Transfer.create(
      amount: (@listing.price * 95).floor,
      currency: 'usd',
      destination: @seller.recipient
      )

    respond_to do |format|
      if @order.save
        format.html { redirect_to root_url }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<br/>
<br/>
<br/>
<p>Copyright 2020</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container">
    <a class="navbar-brand" href="/">EtsyDemo</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to 'About', pages_about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Contact', pages_contact_path, class: 'nav-link' %>
        </li>
      </ul>
      <ul class="navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Seller Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Manage Listings', seller_path, class: 'dropdown-item' %>
              <%= link_to 'Sales History', sales_path, class: 'dropdown-item' %>
            </div>
          </li>

          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to 'Purchase History', purchases_path, class: 'dropdown-item' %>
              <%= link_to 'Edit Profile', edit_user_registration_path, class: 'dropdown-item' %>
              <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item' %>
            </div>
          </li>

        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Etsydemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= tag :meta, name: 'stripe-key', content: ENV["STRIPE_PUBLIC_KEY"] %>
  </head>

  <body>
    <%= render 'layouts/header' %>
      <br/>
      <div class="container-fluid">
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissable">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg, :id => "flash_#{name}" %>
            </div>
          <% end %>
        <% end %>
      </div>
      <br/>
      <div class="container">      
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true, id: 'new_listing', html: { multipart: true }) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      <h4><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image, class: 'form-control' %>
  </div>

  <% if current_user.recipient.blank? %>
    <br/>
    <h1>Bank Account Information</h1>

    <div class="form-group">
      <%= label_tag :country %>
      <%= text_field_tag :country, nil, { name: nil, 'data-stripe': "country", class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= label_tag :routing_number %>
      <%= text_field_tag :routing_number, nil, { name: nil, 'data-stripe': "routingNumber", class: 'form-control' } %>
    </div>

    <div class="form-group">
      <%= label_tag :account_number %>
      <%= text_field_tag :account_number, nil, { name: nil, 'data-stripe': "accountNumber", class: 'form-control' } %>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Show', @listing, class: 'btn btn-link' %> |
<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/index.html.erb
</div>
  <div class="jumbotron jumbotron-fluid text-light text-right">
    <div class="container">
      <h1>Handcrafted items from around the world.</h1><br/>
      <h2>Discover one-of-a-kind items</h2>
    </div>
  </div>

<div class="container">
  <div class="card-columns text-center">
    <% @listings.each do |listing| %>
      <div class="card">
        <% if listing.image.attached? %>
          <%= image_tag listing.image, class: 'card-img-top' %>
        <% else %>
          <%= image_tag 'default-image.jpg', class: 'card-img-top' %>
        <% end %><br/>
        <div class="card-body">
          <h2><%= listing.name %></h2><br/>
          <p><%= number_to_currency listing.price %></p>
          <p><%= "Sold by #{listing.user.name}" %></p>
            <%= link_to 'Show', listing, class: 'btn btn-link stretched-link' %>
        </div>
      </div>
    <% end %>
  </div>

  <br/>

  <% if user_signed_in? %>
    <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { turbolinks: false } %>
  <% end %>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <tr class="text-center">
    <th>Image</th>
    <th>Name</th>
    <th>Description</th>
    <th>Price</th>
    <th>Action</th>
  </tr>


  <% @listings.each do |listing| %>
  <tr>
    <td><%= image_tag listing.image.variant(resize: '75x') %></td>
    <td><%= listing.name %></td>
    <td><%= listing.description %></td>
    <td><%= number_to_currency listing.price %></td>
    <td>
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
          <div class="dropdown-menu">
            <%= link_to 'View', listing, class: 'btn btn-link dropdown-item' %>
            <%= link_to 'Edit', edit_listing_path(listing), class: 'btn btn-link dropdown-item' %>
            <%= link_to 'Destroy', listing, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-link dropdown-item' %>
          </div>
        </div>
      </div>
    </td>
  </tr>
  <% end %>
</table>

<br/>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { turbolinks: false } %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
	<div class="col-md-6">
		<% if @listing.image.attached? %>
			<%= image_tag @listing.image.variant(resize: '400x') %>
		<% else %>
			<%= image_tag 'default-image.jpg' %>
		<% end %>
	</div>
	<div class="col-md-6">
		<h3><%= @listing.name %> </h3>
		<p><%= number_to_currency @listing.price %></p>
		<p><%= @listing.description %></p>
		<div class="text-center">
			<%= link_to "Buy It Now", new_listing_order_path(@listing), class: 'btn btn-success w-75', data: { turbolinks: false } %>
		</div>
	</div>
</div>

<% if current_user == @listing.user %>
	<%= link_to 'Edit', edit_listing_path(@listing), class: 'btn btn-link' %> |
<% end %>
<%= link_to 'Back', listings_path, class: 'btn btn-link' %>

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <%= image_tag @listing.image.variant(resize: '350x') %><br/><br/>
    <h3><%= @listing.name %></h3>
    <h5><%= number_to_currency @listing.price %></h5>
  </div>
  <div class="col-md-8">
    <%= form_with(model: [@listing, @order], local: true, id: 'new_order', class: 'new_order') do |form| %>
      <% if order.errors.any? %>
        <div id="error_explanation" class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          <h4><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h4>

          <ul>
          <% order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>
      
      <div class="form-group">
        <%= form.label :address %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :city %>
        <%= form.text_field :city, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :state %>
        <%= form.text_field :state, class: 'form-control' %>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-md-8">
            <%= label_tag :card_number, "Credit Card Number" %>
            <%= text_field_tag :card_number, nil, { name: nil, 'data-stripe': "number", class: 'form-control' } %>
          </div>
          <div class="col-md-4">
            <%= label_tag :card_code, "CVC" %>
            <%= text_field_tag :card_code, nil, { name: nil, 'data-stripe': "cvc", class: 'form-control' } %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-md-3">
            <%= select_month nil, { use_two_digit_numbers: true }, { name: nil, 'data-stripe': "exp-month", class: 'form-control' } %>
          </div>
          <div class="col-md-3">
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { name: nil, 'data-stripe': "exp-year", class: 'form-control' } %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= form.submit "Complete Order", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form', order: @order %>

<%= link_to 'Back', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="text-center">
  <h2>Your Purchase History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr class="text-center">
    <th>Image</th>
    <th>Item</th>
    <th>Price</th>
    <th>Seller</th>
    <th>Date Purchased</th>
  </tr>


  <% @orders.each do |o| %>
  <tr class="text-center">
    <td><%= image_tag o.listing.image.variant(resize: '75x') %></td>
    <td><%= o.listing.name %></td>
    <td><%= number_to_currency o.listing.price %></td>
    <td><%= o.seller.name %></td>
    <td><%= o.created_at.strftime("%B %-d, %Y") %></td>
  </tr>
  <% end %>
</table>

<br/>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { turbolinks: false } %>
<% end %>

app/views/orders/sales.html.erb
<div class="text-center">
  <h2>Your Sales History</h2>
</div>

<table class="table table-striped table-bordered">
  <tr class="text-center">
    <th>Image</th>
    <th>Item</th>
    <th>Price</th>
    <th>Customer</th>
    <th>Date Sold</th>
  </tr>


  <% @orders.each do |o| %>
  <tr class="text-center">
    <td><%= image_tag o.listing.image.variant(resize: '75x') %></td>
    <td><%= o.listing.name %></td>
    <td><%= number_to_currency o.listing.price %></td>
    <td><%= o.buyer.name %></td>
    <td><%= o.created_at.strftime("%B %-d, %Y") %></td>
  </tr>
  <% end %>
</table>

<br/>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: 'btn btn-link', data: { turbolinks: false } %>
<% end %>

app/views/pages/about.html.erb
<h1>Welcome to EtsyDemo!</h1>
<h2>EtsyDemo is an online marketplace for buying and selling handmade goods.</h2>

app/views/pages/contact.html.erb
<h1>Email us at abc@etsydemo.com</h1>